#!/usr/bin/env python3
"""Generate pixel-art logos for Scatter app reveal orbs and bar gear.

Same grammar as the plymouth (◉.◉) face: sharp cells, three-tone palette,
amber as the single accent. 16×16 cell grid rendered at 4× scale = 64px.
Each tile is its own PNG with transparent background; the bar stylesheet
provides the surrounding orb.
"""
from pathlib import Path
from PIL import Image, ImageDraw

SCALE = 3   # px per cell — output is GRID*SCALE = 48px, displayed at 48px (1:1)
GRID = 16

AMBER  = (255, 184, 0)
MUTED  = (90, 90, 90)

# Brand primary per app. Same hex values as stylesheet.css orb-ring tints,
# so the icon and ring sing the same note.
BRAND = {
    'scatter-browser': (74, 222, 128),
    'appflowy':        (122, 158, 126),
    'onlyoffice':      (220, 215, 198),
    'zotero':          (200, 148, 26),
    'files':           (106, 140, 170),
    'scatter-code':    (255, 184, 0),
    'claude-code':     (184, 89, 63),
    'terminal':        (74, 222, 128),
    'all-apps':        (245, 242, 234),
    'gear':            (200, 200, 208),
    'bowtie':          (74, 222, 128),  # scatter green — Scatter's face
    'history':         (200, 200, 208),
    # Scatter suite — each app gets its own primary so the reveal grid
    # reads as seven distinct surfaces, not seven copies of the bowtie.
    'schools':         (245, 242, 234),  # paper-white — chalkboard letters
    'studio':          (74, 222, 128),   # scatter green — the brain
    'music':           (180, 140, 240),  # violet — sustained tone
    'write':           (220, 215, 198),  # warm paper — page in lamplight
    'draft':           (255, 184, 0),    # amber — stage spotlight
    'film':            (106, 140, 170),  # cool blue — projector beam
    'stream':          (210, 80, 90),    # coral — on-air light
}

# `#` = brand primary, `@` = amber accent, `.` = transparent, `,` = muted.
# Read each motif as a 16-line, 16-col block. Pixel-art legibility check:
# every motif fits in 14 cells with 1-cell margin so it doesn't kiss the orb.
MOTIFS = {
    # Scatter Browser → globe with equator. The browser opens worlds.
    # Distinctly NOT a bowtie (the bar already has one — duplication is bad).
    'scatter-browser': """
................
.....######.....
....########....
...#####@######.
..######@#######
..######@#######
.######@@@######
.@@@@@@@@@@@@@@.
.######@@@######
..######@#######
..######@#######
...#####@######.
....########....
.....######.....
................
................
""",
    # AppFlowy → spiral notebook. Rings on the left, ruled lines, amber line
    # is whichever line you're writing.
    'appflowy': """
................
................
.@.############.
.@.#..........#.
.@.#.########.#.
.@.#..........#.
.@.#.########.#.
.@.#..........#.
.@.#.@@@@@@@@.#.
.@.#..........#.
.@.#.########.#.
.@.#..........#.
.@.#.######...#.
.@.############.
................
................
""",
    # OnlyOffice → page with a big amber A. Documents = letters.
    'onlyoffice': """
................
.############...
.#..........#...
.#....##....#...
.#...####...#...
.#...####...#...
.#..##..##..#...
.#..##..##..#...
.#..######..#...
.#..######..#...
.#.@@....@@.#...
.#.@@....@@.#...
.#..........#...
.############...
................
................
""",
    # Zotero → single tall book spine, ribbon bookmark, amber title band.
    # Vertical-axis silhouette to read different from the horizontal stack.
    'zotero': """
................
....########....
....#......#....
....#......#....
....#......#....
....#.@@@@.#....
....#.@@@@.#....
....#......#....
....#......#....
....#......#....
....#......#....
....#......#....
....#......#....
....##....##....
....##....##....
....##....##....
""",
    # Files → folder with manila tab and visible papers sticking out.
    'files': """
................
................
....######......
....######......
.###############
.#.....#......#.
.#.@@@@@......#.
.#............#.
.#.@@@@@@@@@@.#.
.#............#.
.#............#.
.#............#.
.#............#.
.#............#.
.###############
................
""",
    # Scatter Code → split screen. Code on the left, amber prompt on the right.
    'scatter-code': """
................
.##############.
.#......#.....#.
.#.####.#.@@..#.
.#......#.....#.
.#.######.....#.
.#......#.....#.
.#.####.#.@@..#.
.#......#.....#.
.#.######.....#.
.#......#.....#.
.#.####.#.@@..#.
.#......#.....#.
.##############.
................
................
""",
    # Claude Code → big (◉ ◉) eyes, no parens. Distinct from the bar bowtie.
    # Pure mascot face; bone pupils with amber spark on the right.
    'claude-code': """
................
................
................
....######......
...########.....
...##....##.....
...##.##.##.....
...########.....
....######......
................
.........######.
........########
........##....##
........##.@@##.
........########
.........######.
""",
    # Terminal → big chevron, amber block-cursor below. Empty space says
    # "command line." Reads completely different from scatter-code's split.
    'terminal': """
................
................
................
.##.............
.####...........
.######.........
.########.......
.##########.....
.##########.....
.########.......
.######.........
.####...........
.##.............
................
.@@@@@@@@.......
................
""",
    # History → chronological list. Amber dot timeline marker, then a row
    # of content. Reads as "past conversations" without needing a label.
    'history': """
................
................
.@##############
................
.@##############
................
.@##############
................
.@##############
................
.@##############
................
.@##############
................
................
................
""",
    # Bowtie: Scatter's face. The bar glyph. Pixel-art so it can never
    # misrender as ">-..." like the text label kept doing in low-res JB Mono.
    'bowtie': """
................
##............##
.##..........##.
..##........##..
...##......##...
....##....##....
.....##..##.....
......@@@@......
.....##..##.....
....##....##....
...##......##...
..##........##..
.##..........##.
##............##
................
................
""",
    # All apps → 3×3 grid of fat squares with one amber. Confidently full
    # (vs. the gear's airy cross). Reads "library, every app".
    'all-apps': """
................
................
.###..###..###..
.###..###..###..
.###..###..###..
................
.###..###..###..
.###..###..###..
.###..###..###..
................
.@@@..###..###..
.@@@..###..###..
.@@@..###..###..
................
................
................
""",
    # Schools → open book with amber bookmark. Lessons live in pages.
    'schools': """
................
................
.##############.
.#.....##.....#.
.#.@@@.##.@@@.#.
.#.....##.....#.
.#.###.##.###.#.
.#.....##.....#.
.#.###.##.###.#.
.#.....##.....#.
.#.###.##.###.#.
.#.....##.....#.
.##############.
....##....##....
................
................
""",
    # Studio → brain/circuit cross. Vertical+horizontal trunk with amber
    # synapse at the crossing. The brain of the suite, per the story line.
    'studio': """
................
.......##.......
.......##.......
....######......
...########.....
..####@@####....
..###@@@@###....
.######@@######.
..###@@@@###....
..####@@####....
...########.....
....######......
.......##.......
.......##.......
................
................
""",
    # Music → quarter note with amber notehead. Single tall stem reads
    # "music" instantly, distinct from any other suite tile.
    'music': """
................
................
......######....
......######....
......##........
......##........
......##........
......##........
......##........
......##........
......##........
....@@@@##......
...@@@@@@##.....
...@@@@@@##.....
....@@@@........
................
""",
    # Write → fountain pen at angle, amber ink dot at the nib. Distraction-
    # free writing — the simplest possible mark.
    'write': """
................
............##..
...........####.
..........######
.........######.
........######..
.......######...
......######....
.....######.....
....######......
...######.......
..######........
.######.........
.####...........
.@@.............
................
""",
    # Draft → masks of theatre, amber smile on the comedy half. Playwriting
    # is Ryann's discipline; the masks plant her flag on this tile.
    'draft': """
................
....##....##....
...####..####...
..######..######
..###@@####@@###
..######..######
..######..######
..######..######
..######..######
..#@##@##@##@##.
..######..######
..######..######
...####..####...
....##....##....
................
................
""",
    # Film → film strip with sprocket holes and amber frame in the middle.
    # Reads as cinema at a glance.
    'film': """
................
.##############.
.#.##.##.##.##.#
.#.##.##.##.##.#
.##############.
.##............#
.##.@@@@@@@@@@.#
.##.@@@@@@@@@@.#
.##.@@@@@@@@@@.#
.##............#
.##############.
.#.##.##.##.##.#
.#.##.##.##.##.#
.##############.
................
................
""",
    # Stream → broadcast tower with amber waves. Streaming = signal going
    # out, distinct from film's contained celluloid frame.
    'stream': """
................
.......##.......
......####......
......####......
.....######.....
.....######.....
.....######.....
....########....
....########....
...##########...
.@..########..@.
@@..########..@@
.@..##....##..@.
....##....##....
....##....##....
....######......
""",
    # Gear → 8 visible teeth around a chunky hex body with an axle hole at
    # center. Reads as a gear at a glance, not as scattered pixels. Teeth
    # are 2-cell wide blocks so they survive scaling. No amber here — the
    # gear is utility chrome, not a hero element.
    'gear': """
................
......####......
......####......
....########....
.##.########.##.
.##.##....##.##.
....##....##....
.######..######.
.######..######.
....##....##....
.##.##....##.##.
.##.########.##.
....########....
......####......
......####......
................
""",
}


def parse(motif):
    rows = [r for r in motif.strip("\n").splitlines()]
    cells = []
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch == '#':
                cells.append((x, y, 'primary'))
            elif ch == '@':
                cells.append((x, y, 'amber'))
            elif ch == ',':
                cells.append((x, y, 'muted'))
    return cells


def render(brand, motif):
    img = Image.new('RGBA', (GRID * SCALE, GRID * SCALE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    primary = BRAND[brand]
    for x, y, role in parse(motif):
        if role == 'primary':
            color = primary + (255,)
        elif role == 'amber':
            color = AMBER + (255,)
        else:
            color = MUTED + (255,)
        d.rectangle(
            (x * SCALE, y * SCALE, (x + 1) * SCALE - 1, (y + 1) * SCALE - 1),
            fill=color,
        )
    return img


def main():
    out = Path(__file__).resolve().parent / 'icons'
    out.mkdir(exist_ok=True)
    for brand, motif in MOTIFS.items():
        img = render(brand, motif)
        img.save(out / f'{brand}.png')
    print(f"wrote {len(MOTIFS)} icons to {out}")


if __name__ == '__main__':
    main()
